(() => {
  'use strict';
  const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
  const names=['教室里的日常','出门就是好心情','冬日暖暖','好好吃饭','夜色正好','运动一下'];
  const runner=new Image();runner.src='assets/runner.webp';const portrait=new Image();portrait.src='assets/zhizhi.webp';
  const memoryImages=names.map((_,i)=>{const img=new Image();img.src=`assets/memory-${i+1}.jpg`;return img;});
  const readNumber=key=>{try{const value=Number(localStorage.getItem(key));return Number.isFinite(value)&&value>0?value:0;}catch{return 0;}};
  let best=readNumber('zhizhi-best'),unlocked=Math.min(6,Math.floor(best/100));
  let W=1000,H=510,ground=420,mode='ready',distance=0,coins=0,health=3,elapsed=0,speed=360,spawn=1.7,last=0,scroll=0,invulnerable=0,recovery=0;
  let obstacles=[],stars=[],particles=[],player={x:150,y:0,vy:0,jumps:0,size:120},sound=false,audioContext,toastTimer;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  function resize(){const rect=canvas.getBoundingClientRect();W=rect.width;H=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ground=H*.82;player.x=W<650?W*.21:W*.17;player.size=W<650?94:124;draw();}
  function beep(frequency=550,duration=.08){if(!sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(frequency,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(frequency*.7,audioContext.currentTime+duration);gain.gain.setValueAtTime(.055,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+duration);}catch{sound=false;updateSound();}}
  function updateSound(){$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('sound').innerHTML=`♪<span>音效${sound?'开':'关'}</span>`;}
  function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2500);}
  function renderPhotos(){$('photos').replaceChildren();names.forEach((name,i)=>{const open=i<unlocked,button=document.createElement('button');button.className=`photo-card${open?'':' locked'}`;button.setAttribute('aria-label',open?`查看回忆：${name}`:`${name}，奔跑 ${(i+1)*100} 米解锁`);button.innerHTML=`<div class="photo-image"><img src="assets/memory-${i+1}.jpg" alt="${open?name:''}" loading="lazy">${open?'':`<span class="lock-label"><b>⌑</b>${(i+1)*100} m 解锁</span>`}</div><span class="photo-name">${name}<small>${String(i+1).padStart(2,'0')}</small></span>`;button.addEventListener('click',()=>{if(i>=unlocked){toast(`跑到 ${(i+1)*100} 米，就能打开这张回忆啦`);return;}if(mode==='running')pause();$('full-photo').src=`assets/memory-${i+1}.jpg`;$('full-photo').alt=name;$('photo-caption').textContent=name;$('photo-dialog').showModal();});$('photos').append(button);});$('memory-count').textContent=`${unlocked} / 6`;}
  function updateHud(){$('distance').textContent=Math.floor(distance);$('coins').textContent=coins;$('best').textContent=Math.floor(best);$('lives').textContent='♥'.repeat(health)+'♡'.repeat(3-health);$('lives').setAttribute('aria-label',`剩余 ${health} 次机会`);}
  function saveProgress(){best=Math.max(best,Math.floor(distance));try{localStorage.setItem('zhizhi-best',String(best));}catch{}const next=Math.min(6,Math.floor(best/100));if(next>unlocked){unlocked=next;renderPhotos();toast(next===6?'全部回忆已解锁，继续奔向快乐！':`新回忆：${names[next-1]}，已解锁！`);beep(1050,.2);}}
  function start(){mode='running';distance=coins=elapsed=scroll=invulnerable=recovery=0;health=3;obstacles=[];stars=[];particles=[];spawn=1.25;player.y=player.vy=player.jumps=0;$('start-screen').classList.add('hidden');$('overlay').classList.add('hidden');$('toast').classList.add('hidden');$('pause').disabled=false;$('game').focus({preventScroll:true});updateHud();beep(650,.12);}
  function jump(){if(mode!=='running')return false;player.vy=player.jumps===0?-620:-550;player.jumps++;burst(player.x+player.size*.4,ground-player.y,6,'#f9f8d6');beep(player.jumps===1?650:850);return true;}
  function pause(){if(mode!=='running')return false;mode='paused';saveProgress();$('overlay-title').textContent='快乐暂停中';$('result-kicker').textContent='TAKE A LITTLE BREAK';$('result-detail').textContent='准备好了，就继续出发。';$('result-stats').textContent='';$('resume').innerHTML='继续奔跑 <span>↗</span>';$('restart').classList.remove('hidden');$('overlay').classList.remove('hidden');$('resume').focus({preventScroll:true});return true;}
  function resume(){if(mode==='over'){start();return true;}if(mode!=='paused')return false;mode='running';$('overlay').classList.add('hidden');$('game').focus({preventScroll:true});return true;}
  function gameOver(){mode='over';const record=distance>best;saveProgress();$('pause').disabled=true;$('result-kicker').textContent=record?'NEW PERSONAL BEST':'EVERY RUN COUNTS';$('overlay-title').textContent=record?'之之，又突破啦！':'这一路，也很精彩';$('result-detail').textContent='拍拍灰尘，下一次可以跑得更远。';$('result-stats').innerHTML=`<div><strong>${Math.floor(distance)}</strong>本次距离 / m</div><div><strong>${coins}</strong>收集星星</div>`;$('resume').innerHTML='再跑一次 <span>↗</span>';$('restart').classList.add('hidden');$('overlay').classList.remove('hidden');$('resume').focus({preventScroll:true});beep(170,.25);}
  function burst(x,y,count,color){if(reduced)return;for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*150,vy:-Math.random()*130,life:.55,color});}
  function addObstacle(x=W+60){const phase=Math.min(4,Math.floor(distance/180)),height=elapsed<4?42:42+Math.random()*(34+phase*5);obstacles.push({x,w:38,h:height,hit:false});const y=ground-85-Math.random()*65;for(let i=0;i<3;i++)stars.push({x:x+i*48,y:y-Math.sin(i*Math.PI/2)*18,taken:false});}
  function addPattern(){const phase=Math.min(4,Math.floor(distance/180));addObstacle();if(phase>=1&&Math.random()<Math.min(.72,.18*phase)){const gap=145+phase*12;addObstacle(W+60+gap);if(phase>=3&&Math.random()<.28)addObstacle(W+60+gap*2);}}
  function update(dt){elapsed+=dt;const phase=Math.min(5,Math.floor(distance/180)),base=(W<650?260:350)+Math.min(200,elapsed*3.5)+phase*12;recovery=Math.max(0,recovery-dt);speed=base*(recovery>0?.82:1);distance+=dt*speed/12;scroll+=dt*speed;spawn-=dt;invulnerable=Math.max(0,invulnerable-dt);player.vy+=1650*dt;player.y-=player.vy*dt;if(player.y<=0){player.y=0;player.vy=0;player.jumps=0;}if(spawn<=0){addPattern();spawn=Math.max(.72,1.22-phase*.13)+Math.random()*.2;}
    const px=player.x+player.size*.21,py=ground-player.y-player.size*.81,pw=player.size*.58,ph=player.size*.75;
    for(const o of obstacles){o.x-=speed*dt;if(!o.hit&&invulnerable<=0&&px<o.x+o.w-3&&px+pw>o.x+3&&py<ground&&py+ph>ground-o.h+5){o.hit=true;health--;invulnerable=.45;recovery=1.2;burst(px,py+ph,12,'#efbb66');beep(200,.15);if(health===0){gameOver();break;}toast(`小心障碍，还剩 ${health} 次机会`);}}
    for(const s of stars){s.x-=speed*dt;if(!s.taken&&s.x>px-18&&s.x<px+pw+18&&s.y>py-15&&s.y<py+ph+15){s.taken=true;coins++;burst(s.x,s.y,7,'#e8ad36');beep(1000,.07);}}
    obstacles=obstacles.filter(o=>o.x>-100);stars=stars.filter(s=>s.x>-30&&!s.taken);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=400*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);if(Math.floor(distance/100)>Math.floor(best/100))saveProgress();updateHud();}
  function rounded(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
  function star(x,y,r){ctx.save();ctx.translate(x,y);ctx.fillStyle='#efb73e';ctx.strokeStyle='#fff4b0';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.45:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
  function draw(){ctx.clearRect(0,0,W,H);const sky=ctx.createLinearGradient(0,0,W,H);sky.addColorStop(0,'#edf3e1');sky.addColorStop(1,'#d5e8c7');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#c8dbb65c';ctx.beginPath();ctx.arc(W*.86,H*.36,140,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c4d8b580';ctx.font=`900 ${W<650?85:160}px sans-serif`;ctx.fillText('KEEP RUNNING',-(scroll*.12)%(W+450)+45,H*.56);
    ctx.fillStyle='#c0d7a9';ctx.fillRect(0,ground-44,W,44);ctx.fillStyle='#abc990';ctx.fillRect(0,ground-19,W,19);ctx.fillStyle='#729655';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#e1f1b5';ctx.fillRect(0,ground,W,6);ctx.fillStyle='#426d4e';ctx.fillRect(0,ground+40,W,H-ground-40);ctx.fillStyle='#d5e7ba80';for(let x=-(scroll*.9)%110;x<W;x+=110)ctx.fillRect(x,ground+24,48,3);
    if(mode==='ready')return;
    const landmarkStep=520;for(let i=0;i<3;i++){const x=W+150+i*landmarkStep-(scroll*.35)%(landmarkStep*3);const idx=(Math.floor(scroll*.35/(landmarkStep*3))*3+i)%6;if(x>-150&&x<W+150&&memoryImages[idx].complete&&memoryImages[idx].naturalWidth){ctx.save();ctx.globalAlpha=.75;ctx.translate(x,ground-98);ctx.rotate(-.04);rounded(-34,-75,68,85,4,'#fffff4');ctx.save();ctx.beginPath();ctx.rect(-29,-70,58,65);ctx.clip();const im=memoryImages[idx],scale=Math.max(58/im.width,65/im.height);ctx.drawImage(im,-29+(58-im.width*scale)/2,-70+(65-im.height*scale)/2,im.width*scale,im.height*scale);ctx.restore();ctx.restore();}}
    for(const s of stars)star(s.x,s.y+Math.sin(elapsed*4+s.x*.02)*3,12);
    for(const o of obstacles){rounded(o.x-3,ground-o.h,o.w+6,o.h,5,o.hit?'#bc9b72':'#e99b4f');rounded(o.x+2,ground-o.h+9,o.w-4,9,2,'#fff2c6');ctx.fillStyle='#b5753f';ctx.fillRect(o.x-5,ground-5,o.w+10,5);}
    ctx.save();ctx.globalAlpha=.15;ctx.fillStyle='#244d32';ctx.beginPath();ctx.ellipse(player.x+player.size*.5,ground+4,player.size*.3*(1-player.y/450),6,0,0,Math.PI*2);ctx.fill();ctx.restore();
    ctx.save();if(invulnerable>0&&Math.floor(elapsed*12)%2)ctx.globalAlpha=.35;const bob=player.y===0&&!reduced?Math.sin(elapsed*18)*3:0;ctx.translate(player.x+player.size/2,ground-player.y-player.size/2+bob);ctx.rotate(player.y>0?-.10:reduced?0:Math.sin(elapsed*18)*.035);if(runner.complete&&runner.naturalWidth){const rw=player.size*runner.width/runner.height;ctx.drawImage(runner,-rw/2,-player.size/2,rw,player.size);}else if(portrait.complete&&portrait.naturalWidth){ctx.drawImage(portrait,-player.size*.46,-player.size*.5,player.size*.92,player.size);}else{ctx.fillStyle='#204f3a';ctx.beginPath();ctx.ellipse(0,0,player.size*.3,player.size*.48,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7ebd3';ctx.beginPath();ctx.arc(0,-player.size*.12,player.size*.19,0,Math.PI*2);ctx.fill();}ctx.restore();
    particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/.55);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5);});ctx.globalAlpha=1;
    ctx.fillStyle='#48633d';ctx.font='12px "Microsoft YaHei",sans-serif';if(elapsed<5){ctx.textAlign='center';ctx.fillText('空中连续点按，可以一直连跳',W/2,ground-190);ctx.textAlign='left';}
  }
  function frame(time){const dt=Math.min((time-last)/1000,.032);last=time;if(mode==='running')update(dt);draw();requestAnimationFrame(frame);}
  $('start').addEventListener('click',start);$('jump').addEventListener('click',()=>{if(mode==='ready')start();else jump();});canvas.addEventListener('pointerdown',event=>{if(event.button===0){event.preventDefault();jump();}});$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('restart').addEventListener('click',start);$('sound').addEventListener('click',()=>{sound=!sound;updateSound();beep();});$('close-photo').addEventListener('click',()=>$('photo-dialog').close());$('photo-dialog').addEventListener('click',event=>{if(event.target===$('photo-dialog'))$('photo-dialog').close();});
  document.addEventListener('keydown',event=>{if($('photo-dialog').open)return;if(event.code==='KeyP'||event.code==='Escape'){if(mode==='running'){event.preventDefault();pause();}else if(mode==='paused'){event.preventDefault();resume();}return;}if(event.code!=='Space'&&event.code!=='ArrowUp')return;if(event.target instanceof HTMLElement&&event.target.closest('button,a,input,textarea,select'))return;event.preventDefault();if(event.repeat)return;if(mode==='ready')start();else if(mode==='running')jump();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='running')pause();});window.addEventListener('pagehide',saveProgress);window.addEventListener('resize',()=>{if(mode==='running')pause();resize();});
  const state=()=>({status:mode,distance:Math.floor(distance),stars:coins,lives:health,best:Math.floor(best),unlockedMemories:unlocked,jumps:player.jumps});
  if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=(tool)=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_run_state',description:'Read the current run status, distance, stars, remaining chances and unlocked memories.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:state});register({name:'control_run',description:'Start a new run, jump, pause or resume the same game controlled by the page buttons. Starting resets the current run.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','jump','pause','resume']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['start','jump','pause','resume'].includes(input.action)||Object.keys(input).some(k=>k!=='action'))throw new Error('Invalid action');const fn={start,jump,pause,resume}[input.action];const result=fn();if(result===false)throw new Error('Action unavailable in the current game state');updateHud();draw();return state();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
  const lives=document.createElement('span');lives.id='lives';lives.className='lives';$('pause').before(lives);$('game').tabIndex=-1;renderPhotos();updateHud();resize();requestAnimationFrame(frame);
})();
